version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout  # Pull the latest version of the repository
      - restore_cache:
          keys:
            - v1-backend-dependencies-{{ checksum "APDS APP/PAYMENTSYSTEM/backend/package.json" }}
            - v1-backend-dependencies-
      - run:
          name: Install Backend Dependencies
          command: npm install --prefix "APDS APP/PAYMENTSYSTEM/backend"  # Install only backend dependencies
      - save_cache:
          paths:
            - "APDS APP/PAYMENTSYSTEM/backend/node_modules"
          key: v1-backend-dependencies-{{ checksum "APDS APP/PAYMENTSYSTEM/backend/package.json" }}
      - run:
          name: Run Backend Tests
          command: npm test --prefix "APDS APP/PAYMENTSYSTEM/backend"  # Run backend tests

  deploy:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            echo "Deploying to production..."
            # Add your deployment commands here (e.g., deploying to a cloud provider)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
