version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17-browsers  
    steps:
      - checkout # Pull the latest version of the repository
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            echo "Deploying to production..."
            # Add your deployment commands here (e.g., deploying to a cloud provider)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
