name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud Scanner
        env:
            SONAR_TOKEN: '3c06387dfb429ca4857d04ff86532bbc60476530' 
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=ST10073908_APDS7311_INNOVETIVE- \
            -Dsonar.organization=payshere \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=. \
            -Dsonar.exclusions=backend/node_modules/**,**/*.test.js \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=-
